### ISSUE TITLE
TypeError: Teamrecords.__init__() got an unexpected keyword argument 'eliminationnumbersport' #120

### ISSUE THREAD

**Issue by martinmccarthy** [zero-sum-seattle/mlb-stats_api#195]
Looks like the MLB API was updated, this was the call I was doing:
`current_al_standings = mlb.get_standings(league_id = 103, season = 2023)`

**Comment by KCNilssen** [comment]
We can see that on our side as well, should be an easy fix. I'll try to get something out today. Thanks for the heads up!
